[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "runpyke"
version = "202407"
requires-python = ">= 3.11"
description = "Allow running pip for python interpreter defined by jupyter kernel."

[project.scripts]
runpyke = "runpyke:main"
