[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dkp"
version = "202405"
requires-python = ">= 3.11"
description = "Allow running pip for python interpreter defined by jupyter kernel."

[project.scripts]
dkp = "dkp:main"
